### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Lebowski10** [Porkepik/map#1]
Sorry, I know this is not the place but Idk where else to ask. What happened to the letterboxd discord bot? it was cool and I miss it.

**Comment by Porkepik** [comment]
I'm not hosting the Letterboxd Bot myself anymore, but someone else does: https://discordapp.com/oauth2/authorize?client_id=581122842436042752&scope=bot&permissions=92160
This is not under my control though, and the person can modify its code at their discretion, but I doubt it's any different from mine.

Are you asking for the source code? I'm not hosting it on GitHub anymore, but there are [some forks lying around](https://github.com/Pyrrolidine/letterboxd-bot) and I'll happily share my copy of the source code in a .zip, just not in a GitHub repo.

**Comment by Lebowski10** [comment]
THANK YOU SO MUCH. I was just asking for the bot but if you wanna share your code I would take it, not to do anything with it, just to save it in case the other person decides to not host it anymore. Again, thanks so much and sorry again I know this is not the place to be asking that.

**Comment by Porkepik** [comment]
source files with most recent edits: https://drive.google.com/open?id=1sBZjHiaveQkZh9BFBgD5jIZYL3lv_NDC
